name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@master
      - uses: ./.github/actions/bundler
      - run: bundle exec rake db:setup
      - run: bundle exec rake spec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@master
      - uses: ./.github/actions/bundler
      - run: bundle exec rubocop
